### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by zsnlsw** [wistbean/learn_python3_spider#27]
发生异常: TypeError
object of type 'NoneType' has no len()
  File "C:\Users\tkomg\py\doubanTop250.py", line 40, in get_page_urls
    soup = BeautifulSoup(html, 'lxml')
  File "C:\Users\tkomg\py\doubanTop250.py", line 91, in <module>
    list_page_urls = get_page_urls()

有错误

**Comment by millenniumparade** [comment]
request_page() 里面request的时候传一个header进去
<img width="1261" alt="Screen Shot 2020-08-29 at 11 09 47 PM" src="https://user-images.githubusercontent.com/14156271/91650368-bd25b300-ea4c-11ea-8792-5285a9736841.png">
